import { IndexEntry } from './types';

export const masterIndex: IndexEntry[] = [
  // Page 1
  { topic: "acidic cleaners", book: "CM", page: "16, 18, 25–6, 29, 31–3, 43, 56, 64, 68, 76, 78, 116–18, 152–3, 182" },
  { topic: "acidic stains", book: "BG", page: "61" },
  { topic: "acidic stains", book: "CM", page: "25" },
  { topic: "acids", book: "CM", page: "12, 16, 43, 45" },
  { topic: "Acton, Eliza, Modern Cookery", book: "GL", page: "6" },
  { topic: "Agas", book: "BG", page: "10–11, 160, 223" },
  { topic: "Agas", book: "CM", page: "97–101, 104" },
  { topic: "air fresheners", book: "CG", page: "179" },
  { topic: "air fresheners", book: "CM", page: "20, 177–8" },
  { topic: "deodorizing room and fabric spray", book: "CG", page: "182–4" },
  { topic: "air fryers", book: "GK", page: "11" },
  { topic: "algae", book: "CM", page: "23, 28, 68–9, 72–4" },
  
  // Page 2
  { topic: "alkaline cleaners", book: "CM", page: "31, 78, 116–18, 152–3" },
  { topic: "alkalines", book: "CM", page: "16, 43, 45, 56" },
  { topic: "All-purpose floor cleaner", book: "CM", page: "19–20, 183" },
  { topic: "All-purpose spray cleaner", book: "BG", page: "13–14" },
  { topic: "All-purpose spray cleaner", book: "CM", page: "16–18, 20, 24–5, 43, 45, 109, 120, 131, 175, 183, 184" },
  { topic: "All-purpose spray cleaner recipe", book: "CM", page: "10–11" },
  { topic: "almond sponge", book: "SD", page: "352–5" },
  { topic: "baby cherry, chocolate and almond biscotti", book: "SD", page: "49–50" },
  { topic: "cheat almond tarts", book: "SD", page: "268–70" },
  { topic: "cherry almond traybake", book: "SD", page: "134–6" },
  { topic: "half-sugar almond meringues", book: "SD", page: "338–9" },
  { topic: "muesli", book: "GK", page: "221" },
  { topic: "raspberry & almond bread & butter pudding", book: "GK", page: "34" },
  { topic: "raspberry and almond muffins", book: "BG", page: "163–5" },
  { topic: "almond milk, flexi rice pudding", book: "BG", page: "257–60" },
  { topic: "aloe vera gel, reusable wet wipes", book: "BG", page: "139–41" },
  { topic: "aluminium", book: "CM", page: "18, 23, 102, 107–8, 174" },
  { topic: "anti-bac", book: "CM", page: "24, 33, 120, 134, 206, 222, 241, 253, 257, 274, 279" },
  { topic: "ants", book: "CM", page: "25, 166, 199" },
  { topic: "aphids", book: "GH", page: "112, 115, 124, 181, 247, 248, 297" },
  { topic: "eco-friendly pesticides", book: "CG", page: "216–18" },
  { topic: "apple", book: "GH", page: "189" },
  { topic: "apple charlotte", book: "SD", page: "323–5" },
  { topic: "apple and cinnamon scones", book: "SD", page: "62–3" },
  { topic: "apple sauce", book: "GK", page: "181" },
  { topic: "dried apple slices", book: "GH", page: "207–9" },
  { topic: "Eve’s pudding", book: "SD", page: "321–2" },
  { topic: "fruit crumble", book: "SD", page: "329–30" },
  { topic: "fruit pudding", book: "SD", page: "305–6" },
  { topic: "gluten-free bread & butter pudding", book: "GK", page: "35–6" },
  { topic: "granola Sunday sundae", book: "GK", page: "226" },
  { topic: "harvesting and storing apples", book: "GH", page: "204–7, 304" },
  { topic: "mock Eve’s Pudding", book: "BG", page: "179–81" },
  { topic: "offcuts pudding", book: "GK", page: "38" },
  { topic: "overnight oats", book: "GK", page: "222" },
  { topic: "parsnip & apple soup", book: "GK", page: "57" },
  { topic: "pecan and apple cake", book: "SD", page: "182–4" },
  { topic: "pie fillings", book: "BG", page: "209" },
  { topic: "queen of puddings", book: "SD", page: "326–8" },
  { topic: "savoury stuffing crowd-pleaser", book: "GK", page: "192" },
  { topic: "single-serve whole apple and blackberry pies", book: "SD", page: "249–51" },
  { topic: "tarte tatin", book: "SD", page: "296–8" },
  { topic: "thinning and pruning apples", book: "GH", page: "143–4, 205, 216–17" },
  { topic: "two-ingredient chocolate pots", book: "GK", page: "144" },
  { topic: "Viennese tart", book: "SD", page: "265–7" },
  { topic: "apple juice", book: "GK", page: "66, 226, 222, 182" },
  { topic: "apricot", book: "GH", page: "10, 201–2, 207, 248–9" },
  { topic: "fruit jam", book: "GK", page: "241–2" },
  { topic: "granola", book: "GK", page: "225" },
  { topic: "luxury deep-filled mince pies", book: "BG", page: "289–94" },
  { topic: "mini Simnel cakes", book: "GK", page: "167–8" },
  { topic: "muesli", book: "GK", page: "221" },
  { topic: "peppered pork with fruit", book: "GK", page: "182, 184" },
  { topic: "aquafaba, chocolate mousse", book: "BG", page: "248–52" },
  { topic: "ash", book: "GH", page: "233" },
  { topic: "astringents", book: "CM", page: "270, 273" },
  { topic: "aubergine", book: "GH", page: "42, 125–6, 166, 189, 88, 95" },

  // Page 3
  { topic: "courgette cannelloni", book: "GK", page: "29–30" },
  { topic: "autumn", book: "GH", page: "187–235" },
  { topic: "Avobenzone", book: "CM", page: "247" },
  { topic: "babies, poosplosions", book: "CM", page: "251–6" },
  { topic: "bacon/bacon lardons", book: "GL", page: "18" },
  { topic: "12–hour slow-cooked ragu", book: "GK", page: "120, 121–2" },
  { topic: "‘all-in-one’ beef bourguignon", book: "GK", page: "62" },
  { topic: "bacteria", book: "CM", page: "26, 33, 120, 206, 237, 273–4" },
  { topic: "bags, cleaning mould and stains", book: "BG", page: "31–2, 79, 118–20" },
  { topic: "bains marie", book: "GK", page: "34, 36" },
  { topic: "bains marie", book: "SD", page: "314" },
  { topic: "baked potatoes, budget", book: "BG", page: "169–71" },
  { topic: "baking parchment, reusable", book: "GL", page: "16" },
  { topic: "baking powder", book: "CM", page: "12" },
  { topic: "baking sheets, ad hoc", book: "SD", page: "32" },
  { topic: "balsamic-glazed slow-roast brisket of beef with Yorkshire puddings", book: "GK", page: "188, 189–90" },
  { topic: "bananas", book: "CM", page: "120" },
  { topic: "Barbados banana bread", book: "SD", page: "132–3" },
  { topic: "freezing bananas", book: "SD", page: "133" },
  { topic: "quick banana muffins", book: "GK", page: "100, 101" },
  { topic: "barbecues, cleaning racks with grass", book: "CG", page: "87" },
  { topic: "Basic Magic", book: "CM", page: "13, 16–18, 20–3, 25, 29, 43–8, 56, 74, 78, 99, 173" },
  { topic: "Basic Magic floor cleaner", book: "CM", page: "47, 48" },
  { topic: "Basic Magic kitchens", book: "CM", page: "131" },
  { topic: "Basic Magic recipe", book: "CM", page: "44" },
  { topic: "Basic Magic sinks", book: "CM", page: "109, 110, 111" },
  { topic: "Basic Magic slime stains", book: "CM", page: "257–8" },
  { topic: "Basic Magic stone bird baths", book: "CM", page: "72" },
  { topic: "basil", book: "GH", page: "42, 88, 213, 261" },
  { topic: "basil", book: "GL", page: "305" },
  { topic: "baked stuffed tomatoes", book: "GK", page: "41" },
  { topic: "Mediterranean chicken with sweet peppers", book: "GK", page: "132" },
  { topic: "propagating basil", book: "GH", page: "107–8" },
  { topic: "sowing basil", book: "GH", page: "83" },
  { topic: "storing basil", book: "GH", page: "146–8" },
  { topic: "bath salts, perfumed and coloured", book: "CG", page: "253–5" },
  { topic: "bath and shower gel", book: "CG", page: "250–2" },
  { topic: "bathrooms", book: "CG", page: "108–9, 190–211, 270–1, 272" },
  { topic: "bathrooms", book: "CM", page: "29, 30" },
  { topic: "baths acrylic", book: "CM", page: "22" },
  { topic: "baths cleaning", book: "CM", page: "21–2, 27, 30, 47, 55" },
  { topic: "baths taking", book: "CM", page: "159–60" },
  { topic: "batteries", book: "GL", page: "90" },
  { topic: "beans", book: "GH", page: "298, 299, 301" },
  { topic: "blanching and freezing beans", book: "GH", page: "151–2" },
  { topic: "companion planting beans", book: "GH", page: "115, 118, 119, 126, 141" },
  { topic: "container growing beans", book: "GH", page: "91, 97" },
  { topic: "cooking beans", book: "GH", page: "153" },
  { topic: "coq au leekie bean stew", book: "GK", page: "138" },
  { topic: "dried beans", book: "GH", page: "231–2" },
  { topic: "harvesting beans", book: "GH", page: "139–41, 214" },
  { topic: "pickled beans", book: "GK", page: "236" },
  { topic: "planting out beans", book: "GH", page: "87" },
  { topic: "saving seeds beans", book: "GH", page: "214" },
  { topic: "sowing beans", book: "GH", page: "83, 91, 97, 247" },
  { topic: "supporting beans", book: "GH", page: "91, 102" },
  { topic: "beansprouts, chicken stir-fry", book: "GK", page: "126–7" },
  { topic: "bed warmers", book: "BG", page: "283–5" },

  // Page 4
  { topic: "beef", book: "GK", page: "128" },
  { topic: "12–hour slow-cooked ragu", book: "GK", page: "120, 121–2" },
  { topic: "‘all-in-one’ beef bourguignon", book: "GK", page: "61–2, 63" },
  { topic: "Balsamic-glazed slow-roast brisket of beef with Yorkshire puddings", book: "GK", page: "188, 189–90" },
  { topic: "beef in beer", book: "GK", page: "64, 65" },
  { topic: "meat pie for one", book: "SD", page: "292–5" },
  { topic: "potted meats", book: "GK", page: "16, 17" },
  { topic: "school dinners meat pie", book: "SD", page: "233–7" },
  { topic: "universal cottage pie", book: "GK", page: "27–8" },
  { topic: "beeswax", book: "CM", page: "133–8" },
  { topic: "beeswax bread bags", book: "BG", page: "128–30" },
  { topic: "beeswax wraps", book: "GL", page: "171, 173, 206, 211–13" },
  { topic: "sore and cracked feet cream", book: "BG", page: "147–8" },
  { topic: "Beeton, Mrs", book: "BG", page: "207" },
  { topic: "beetroot", book: "GH", page: "115, 116, 298" },
  { topic: "beetroot salad", book: "GK", page: "170, 171" },
  { topic: "Grandma’s beetroot pickle", book: "GH", page: "175–7" },
  { topic: "harvesting beetroot", book: "GH", page: "106–7, 145, 174–5" },
  { topic: "pickled beetroot", book: "GK", page: "236" },
  { topic: "sowing beetroot", book: "GH", page: "80, 81–2" },
  { topic: "berries", book: "GH", page: "156–9, 238–9, 35–6, 226, 227, 61–3, 155–6, 304" },
  { topic: "breakfast berry jam", book: "GH", page: "156–9" },
  { topic: "fruit ketchup", book: "GK", page: "238–9" },
  { topic: "granola Sunday sundae", book: "GK", page: "226, 227" },
  { topic: "harvesting and storing berries", book: "GH", page: "61–3, 155–6, 304" },
  { topic: "marshmallows", book: "GK", page: "49" },
  { topic: "overnight oats", book: "GK", page: "222" },
  { topic: "simple sherry trifle", book: "GK", page: "198–9" },
  { topic: "strawberries & cream roulade", book: "GK", page: "173" },
  { topic: "best-before dates", book: "CM", page: "131–2" },
  { topic: "BHT (butylated hydroxytoluene)", book: "CM", page: "271–2" },
  { topic: "bicarbonate of soda", book: "CG", page: "12, 14, 15, 144" },
  { topic: "bicarbonate of soda", book: "CM", page: "7, 18, 45, 78, 79–82, 84–5" },
  { topic: "bicarb paste", book: "GL", page: "261–4" },
  { topic: "burnt pans, cooking pots and trays", book: "BG", page: "85–7" },
  { topic: "Cream cleaner", book: "BG", page: "14–15" },
  { topic: "Cream cleaner", book: "CM", page: "11–12" },
  { topic: "Dry cleaning foam", book: "CM", page: "60–3" },
  { topic: "imitation grass", book: "CM", page: "278" },
  { topic: "kitchens", book: "CM", page: "102, 104–6, 140, 146, 151–2, 154" },
  { topic: "laundry", book: "CM", page: "218–20, 225" },
  { topic: "Liquid hand soap", book: "CM", page: "265" },
  { topic: "make-up brush and sponge cleaner", book: "BG", page: "122–3" },
  { topic: "moisture absorber", book: "BG", page: "25–6" },
  { topic: "mould cleaner", book: "BG", page: "24–5, 32" },
  { topic: "odour neutralization", book: "CM", page: "150" },
  { topic: "ovens", book: "CM", page: "102, 104–6" },
  { topic: "powder detergent", book: "BG", page: "58–9" },
  { topic: "sinks", book: "CM", page: "116, 117–18" },
  { topic: "stain remover", book: "BG", page: "38–9, 62" },
  { topic: "Sticky stuff paste", book: "CM", page: "58–9" },
  { topic: "stinky second-hand clothes and furniture", book: "BG", page: "78–80" },
  { topic: "teddy and soft toy cleaner", book: "BG", page: "135–7" },
  { topic: "wood marks", book: "CM", page: "88" },
  { topic: "bin liners", book: "CM", page: "160–1" },
  { topic: "bins", book: "CM", page: "160–3" },
  { topic: "biodegradability", book: "CM", page: "129" },
  { topic: "bird baths, stone", book: "CM", page: "72–3" },
  { topic: "birds", book: "GH", page: "96, 112, 240-1, 297" },
  { topic: "bird deterrents", book: "GH", page: "54–5, 99, 102–3, 191, 275" },
  { topic: "bird feeders", book: "GL", page: "86–9, 312" },
  { topic: "bird poo", book: "CM", page: "47" },
  { topic: "biro stains", book: "BG", page: "118–20" },
  { topic: "biro stains", book: "CM", page: "20, 35" },
  { topic: "biscotti, baby cherry, chocolate and almond", book: "SD", page: "49–50" },
  { topic: "biscuits", book: "GL", page: "148–50" },
  { topic: "biscuits", book: "SD", page: "29–32" },
  
  // Page 5
  { topic: "brandy snaps", book: "SD", page: "42–3" },
  { topic: "chocolate biscuit base", book: "GK", page: "110, 111–13" },
  { topic: "digestive biscuits", book: "SD", page: "200-1" },
  { topic: "flapjacks", book: "SD", page: "40-1" },
  { topic: "hobnobs", book: "SD", page: "51–3" },
  { topic: "lemon shortbread", book: "SD", page: "33–5" },
  { topic: "rose and chocolate macarons", book: "SD", page: "44–8" },
  { topic: "rye and fennel thins", book: "SD", page: "54–5" },
  { topic: "spiced Christmas shortbreads", book: "SD", page: "36–7" },
  { topic: "vanilla shortbread", book: "SD", page: "28–9" },
  { topic: "black spot lichen", book: "CM", page: "70–1" },
  { topic: "blackberry pie", book: "SD", page: "252–4" },
  { topic: "blackberry fruit crumble", book: "SD", page: "329–30" },
  { topic: "blackberry fruit ketchup", book: "GK", page: "238–9" },
  { topic: "blackberry queen of puddings", book: "SD", page: "326–8" },
  { topic: "blackberry single-serve pies", book: "SD", page: "249–51" },
  { topic: "blackcurrants", book: "GH", page: "19–20, 189, 297" },
  { topic: "blackcurrant breakfast berry jam", book: "GH", page: "158–9" },
  { topic: "blackcurrant harvesting and freezing", book: "GH", page: "155, 156" },
  { topic: "blackcurrant pest deterrents", book: "GH", page: "113–14" },
  { topic: "blackcurrant planting", book: "GH", page: "280" },
  { topic: "blackfly", book: "GH", page: "114, 124–5, 297" },
  { topic: "blanching", book: "GH", page: "151–2, 153" },
  { topic: "bleach chlorine", book: "CM", page: "26, 31, 46, 65" },
  { topic: "blight, potato", book: "GH", page: "53–4" },
  { topic: "blinds", book: "CM", page: "170–2" },
  { topic: "blinds mouldy", book: "BG", page: "25, 27, 28–30, 105" },
  { topic: "blockages", book: "CM", page: "93–122" },
  { topic: "bloodstains", book: "BG", page: "62–3, 231" },
  { topic: "bloodstains", book: "CG", page: "50-2" },
  { topic: "bloodstains", book: "CM", page: "211" },
  { topic: "bloodstains", book: "GL", page: "255–6" },
  { topic: "blueberry with citrus posset", book: "SD", page: "366–7" },
  { topic: "blueberry overnight oats", book: "GK", page: "222" },
  { topic: "body odour stains and smells", book: "CG", page: "68–70" },
  { topic: "body odour stains and smells", book: "CM", page: "22, 238, 268–70" },
  { topic: "Body spray", book: "CM", page: "15, 274–5" },
  { topic: "Bodywork solution", book: "CM", page: "20, 174, 176–7" },
  { topic: "bonfires", book: "GH", page: "232–3, 234" },
  { topic: "boots", book: "GH", page: "16, 55–7" },
  { topic: "boulangère potatoes", book: "GL", page: "190-2" },
  { topic: "bowls, drinking/feeding", book: "CM", page: "279" },
  { topic: "brandy, spiced bread", book: "GK", page: "104" },
  { topic: "brass items, cleaning", book: "CG", page: "137–40" },
  { topic: "bread", book: "BG", page: "172–83" },
  { topic: "bread", book: "GK", page: "7, 68, 69–86" },
  { topic: "bread", book: "SD", page: "67–115" },
  { topic: "bread basic white loaf", book: "GK", page: "71–4" },
  { topic: "bread and butter pudding", book: "SD", page: "312–14" },
  { topic: "brioche", book: "SD", page: "110-12" },
  { topic: "bread canapés", book: "BG", page: "176–9" },
  { topic: "Chelsea buns", book: "SD", page: "94–6" },
  { topic: "bread focaccia", book: "GK", page: "78, 79–80" },
  { topic: "bread gluten-free", book: "GK", page: "84–6, 87" },
  { topic: "honey buns", book: "GK", page: "96, 97–8" },

  // Page 6
  { topic: "hot cross buns", book: "SD", page: "90-3" },
  { topic: "bread kneading", book: "GK", page: "72" },
  { topic: "bread kneading", book: "SD", page: "68, 73–4" },
  { topic: "bread ‘knocking back’", book: "GK", page: "73" },
  { topic: "bread rye", book: "GK", page: "81–2, 83" },
  { topic: "bread seed", book: "GL", page: "145–7" },
  { topic: "bread soft white", book: "SD", page: "79–81" },
  { topic: "bread sourdough", book: "SD", page: "97–102" },
  { topic: "bread spiced", book: "GK", page: "64, 104" },
  { topic: "bread wholesome loaf", book: "SD", page: "88–9" },
  { topic: "Yorkshire teacakes", book: "SD", page: "113–15" },
  { topic: "breadcrumbs", book: "BG", page: "173–6" },
  { topic: "golden breadcrumbs", book: "GK", page: "14, 15" },
  { topic: "brick dust, cleaning", book: "BG", page: "38–9" },
  { topic: "broad beans", book: "GH", page: "10, 42, 298" },
  { topic: "broad beans cooking", book: "GH", page: "153" },
  { topic: "broad beans freezing", book: "GH", page: "151" },
  { topic: "broad beans harvesting", book: "GH", page: "139–41" },
  { topic: "broccoli", book: "GH", page: "81, 83, 191, 303" },
  { topic: "bronzer", book: "CM", page: "245–51" },
  { topic: "brownies, chocolate", book: "GK", page: "114, 115" },
  { topic: "brushes cleaning make-up", book: "BG", page: "121–3" },
  { topic: "brushes wooden", book: "GL", page: "98–9" },
  { topic: "buckets", book: "GH", page: "18–19" },
  { topic: "bug stains", book: "CM", page: "174, 175" },
  { topic: "bulbs", book: "GH", page: "41, 92–3, 166–7, 218, 227" },
  { topic: "bulbs spring-flowering", book: "GL", page: "107, 302–4" },
  { topic: "bulk buying", book: "CG", page: "13–14" },
  { topic: "bumps, on cars", book: "CM", page: "175" },
  { topic: "bundt cakes", book: "SD", page: "351–5, 375–7" },
  { topic: "burns/scorches", book: "CM", page: "87, 90–1" },
  { topic: "burnt pans", book: "BG", page: "85–7" },
  { topic: "bushes, trimming", book: "GH", page: "96" },
  { topic: "butter homemade", book: "BG", page: "211–13" },
  { topic: "butter herb and garlic", book: "GH", page: "109–11" },

  // Page 7
  { topic: "butter beans, coq au leekie bean stew", book: "GK", page: "138" },
  { topic: "buttercream", book: "GL", page: "21, 37, 133" },
  { topic: "buttercream", book: "SD", page: "165–6, 186–7, 208–9" },
  { topic: "buttercream chocolate", book: "GK", page: "105–6, 107" },
  { topic: "buttercream chocolate", book: "GL", page: "180-2" },
  { topic: "butterflies", book: "GH", page: "112, 118, 181–2, 297" },
  { topic: "buttermilk", book: "BG", page: "211, 212" },
  { topic: "buttermilk scones", book: "BG", page: "214–15" },
  { topic: "cabbage ‘all-in-red’ braised", book: "GK", page: "185" },
  { topic: "cabbage pickled red", book: "GK", page: "234, 235–6" },
  { topic: "cabbage red coleslaw", book: "GK", page: "194, 195" },
  { topic: "cabbages", book: "GH", page: "10, 42, 301" },
  { topic: "cabbages spring", book: "GH", page: "186, 190-1, 301" },
  { topic: "cake tin calculator table", book: "GL", page: "130, 320-1" },
  { topic: "cakes", book: "SD", page: "117–84" },
  { topic: "cakes carrot and orange", book: "SD", page: "167–9" },
  { topic: "cakes cherry almond traybake", book: "SD", page: "134–6" },
  { topic: "cakes chocolate log", book: "GK", page: "200, 201–3" },
  { topic: "cakes Christmas", book: "BG", page: "276–80" },
  { topic: "cakes coconut & passion fruit angel", book: "GK", page: "45–6, 47" },
  { topic: "cakes courgette cupcakes", book: "GK", page: "108, 109" },
  { topic: "cakes Jamaican-style ginger", book: "GK", page: "102, 103" },
  { topic: "cakes lemon drizzle", book: "SD", page: "130-1" },
  { topic: "cakes malt loaf", book: "SD", page: "205–6" },
  { topic: "cakes mini Simnel", book: "GK", page: "167–8, 169" },

  // Page 8
  { topic: "cakes parsnip chocolate chip loaf", book: "GH", page: "254–6" },
  { topic: "cakes raspberry ripple cupcakes", book: "SD", page: "165–6" },
  { topic: "cakes rich fruit", book: "SD", page: "149–58" },
  { topic: "cakes Victoria sandwich", book: "SD", page: "121–6" },
  { topic: "canapés", book: "BG", page: "176–9" },
  { topic: "caramel sauce", book: "GK", page: "151–2, 153" },
  { topic: "crème caramel", book: "SD", page: "259–62" },
  { topic: "carpets candle wax spills", book: "CG", page: "160-2" },
  { topic: "carpets freshening and dry-cleaning", book: "CG", page: "163–4" },
  { topic: "carpets rust on", book: "CM", page: "74, 76–7" },
  { topic: "carpets spot-cleaning", book: "CG", page: "156–7" },
  { topic: "carrots", book: "BG", page: "204–8" },
  { topic: "carrots", book: "GH", page: "261, 299" },
  { topic: "carrot & coriander soup", book: "GK", page: "54, 55" },
  { topic: "carrot crisps", book: "BG", page: "204" },
  { topic: "carrot crisps", book: "GH", page: "63–4" },
  { topic: "carrot jam", book: "BG", page: "207–8" },
  { topic: "carrot soup", book: "BG", page: "204–6" },
  { topic: "cars", book: "CM", page: "20, 30, 47, 173–8, 183, 237" },
  { topic: "cars de-icer", book: "BG", page: "142–3" },
  { topic: "cars screen wash", book: "BG", page: "144–5" },

  // Page 9
  { topic: "cast iron pans cleaning", book: "CG", page: "128–30" },
  { topic: "cast iron pans renewing", book: "BG", page: "88–9" },
  { topic: "caterpillars", book: "GH", page: "180-1, 215–16, 297" },
  { topic: "cats", book: "CM", page: "232, 279" },
  { topic: "cats deterrents", book: "CG", page: "219–20" },
  { topic: "cauliflowers", book: "GH", page: "42, 81, 83, 112, 118, 119, 299" },
  { topic: "celery", book: "GK", page: "121–2, 62, 54, 126–7, 138, 186–7, 206, 60, 182, 58, 179–80, 21–2, 27–8, 140-1" },
  { topic: "ceramic hobs, cleaning", book: "CG", page: "92–4" },
  { topic: "cheese and onion flan", book: "SD", page: "243–5" },
  { topic: "cheese scones", book: "SD", page: "64–5" },
  { topic: "cheesecakes baked lemon", book: "GK", page: "113" },
  { topic: "cheesecakes baked lime, chocolate & coconut", book: "GK", page: "110, 111–13" },
  { topic: "cherries", book: "GH", page: "247–8" },
  { topic: "cherry Bakewell scones", book: "SD", page: "59–61" },
  { topic: "chewing gum", book: "BG", page: "62, 67–8" },
  { topic: "chicken Kyiv", book: "GK", page: "134, 135" },

  // Page 10
  { topic: "chicken stir-fry", book: "GK", page: "126–7" },
  { topic: "chicken and tarragon pie", book: "SD", page: "238–42" },
  { topic: "cider chicken with mushrooms & tarragon", book: "GK", page: "130, 131" },
  { topic: "chicken-keeping", book: "CM", page: "199–200" },
  { topic: "chillies", book: "GH", page: "95, 125–6, 166, 300, 88, 195, 199–201" },
  { topic: "chives", book: "GH", page: "76, 104–5, 163, 217, 305" },
  { topic: "chocolate brownies", book: "GK", page: "114, 115" },
  { topic: "chocolate ganache", book: "GK", page: "201–3" },
  { topic: "chocolate log", book: "GK", page: "200, 201–3" },
  { topic: "chocolate mousse", book: "BG", page: "248–52" },
  { topic: "chocolate and orange delice", book: "SD", page: "356–8" },
  { topic: "chocolate pastry", book: "SD", page: "255–7, 271–4" },
  { topic: "two-ingredient chocolate pots", book: "GK", page: "144, 145" },

  // Page 11
  { topic: "chopping boards cleaning", book: "BG", page: "94–5, 222" },
  { topic: "chopping boards deodorizing", book: "CG", page: "97–9, 271" },
  { topic: "Christmas cake", book: "BG", page: "276–80" },
  { topic: "Christmas trees", book: "GH", page: "251–3" },
  { topic: "citric acid", book: "CM", page: "7, 43, 56, 83–4, 117" },
  { topic: "citric acid descaling kettles", book: "CM", page: "27" },
  { topic: "citrus crumb", book: "GH", page: "210" },
  { topic: "citrus crumb", book: "GK", page: "102, 226, 227" },
  { topic: "citrus posset with blueberries", book: "SD", page: "366–7" },
  { topic: "cleaning dishwashers", book: "BG", page: "111–14" },
  { topic: "cleaning dishwashers", book: "CG", page: "82–4, 270" },
  { topic: "cleaning floors", book: "CG", page: "173–5, 272" },
  { topic: "cleaning fridges", book: "CG", page: "117–19, 120-2, 270" },
  { topic: "cleaning furniture", book: "BG", page: "78–80" },
  { topic: "cleaning furniture", book: "CG", page: "146–8, 185–6" },

  // Page 12
  { topic: "cleaning leather", book: "BG", page: "31–2, 118–20" },
  { topic: "cleaning leather", book: "CG", page: "181" },
  { topic: "cleaning metal", book: "CG", page: "141–5" },
  { topic: "cleaning microwaves", book: "CG", page: "95–6, 270" },
  { topic: "cleaning oven shelves", book: "CG", page: "85–7" },
  { topic: "cleaning sinks", book: "CG", page: "111–12, 116, 270" },
  { topic: "cleaning toilets", book: "CG", page: "194–201, 270, 272, 273" },
  { topic: "cleaning washing machines", book: "CG", page: "21–4, 270" },
  { topic: "cleaning agents all-purpose spray", book: "BG", page: "13–14" },
  { topic: "cleaning agents mould cleaner", book: "BG", page: "24–5, 27–34" },
  { topic: "cleaning agents polish", book: "BG", page: "15–16, 30-1" },
  { topic: "cleaning agents toilet cleaner", book: "BG", page: "18–19" },
  { topic: "clothing darning", book: "BG", page: "131–4" },
  { topic: "clothing re-waxing jackets", book: "BG", page: "124–7" },

  // Page 13
  { topic: "cobwebs", book: "CM", page: "166–8" },
  { topic: "coconut tarts", book: "SD", page: "268–70" },
  { topic: "coffee machines", book: "GL", page: "234, 235" },
  { topic: "coffee stains", book: "CM", page: "33, 47, 221" },
  { topic: "cold frames", book: "GH", page: "41–2" },
  { topic: "compost", book: "GH", page: "24–36, 213–14, 230, 246" },
  { topic: "compost homemade", book: "GH", page: "25–35, 85–6, 96, 165" },
  { topic: "Conker detergent", book: "CG", page: "33–4" },
  { topic: "Conker detergent mark II", book: "CM", page: "211–14" },

  // Page 14
  { topic: "conversion charts", book: "GK", page: "244–5" },
  { topic: "conversion charts", book: "SD", page: "26–8" },
  { topic: "coq au leekie bean stew", book: "GK", page: "138, 139" },
  { topic: "cordial, lemon and elderflower", book: "GK", page: "177" },
  { topic: "cottage pie, universal", book: "GK", page: "26, 27–8" },
  { topic: "courgettes", book: "GH", page: "127, 139, 154, 189, 261, 298, 299" },
  { topic: "courgette cannelloni", book: "GK", page: "29–30, 31" },
  { topic: "courgette cupcakes", book: "GK", page: "108, 109" },
  { topic: "courgette quiche", book: "SD", page: "246–8" },
  { topic: "craft and creation", book: "GL", page: "101–25" },
  { topic: "cranberries", book: "BG", page: "295–7" },
  { topic: "cranberry sauce", book: "BG", page: "296–7" },
  { topic: "cranberry sauce", book: "GK", page: "149, 185–7" },

  // Page 15
  { topic: "crème brûlée", book: "SD", page: "363–5" },
  { topic: "crème pâtissière", book: "BG", page: "224–5" },
  { topic: "crème pâtissière", book: "SD", page: "196–7, 299–300" },
  { topic: "crisps carrot", book: "BG", page: "204" },
  { topic: "crisps carrot", book: "GH", page: "63–4" },
  { topic: "crisps lemon and pepper kale", book: "GH", page: "253–4" },
  { topic: "crumpets", book: "GK", page: "90, 91–2" },
  { topic: "cucumber", book: "GH", page: "42, 88, 154, 189, 299" },
  { topic: "cucumber pickle", book: "GH", page: "178–80" },
  { topic: "fridge-pickled cucumbers & onions", book: "GK", page: "232, 233" },
  
  // Page 16
  { topic: "cups", book: "CM", page: "32, 47" },
  { topic: "curdling buttercream", book: "GK", page: "106" },
  { topic: "curdling buttercream", book: "GL", page: "33" },
  { topic: "curdling cakes", book: "GK", page: "106" },
  { topic: "curdling Italian meringue buttercream", book: "SD", page: "190" },
  { topic: "lemon curd", book: "BG", page: "187–9, 221–2" },
  { topic: "lemon curd", book: "GL", page: "133–6" },
  { topic: "lemon curd", book: "SD", page: "193–5, 340-2, 343–6" },
  { topic: "passion fruit curd", book: "GK", page: "45–6, 47" },
  { topic: "Eccles cakes", book: "GK", page: "164, 165–6" },
  { topic: "curry all-veggie", book: "GK", page: "32, 33" },
  { topic: "curried ham croquettes", book: "GK", page: "24, 25" },
  { topic: "curry quick & easy", book: "GK", page: "136, 137" },
  { topic: "curry stains", book: "BG", page: "61, 69–70, 93" },
  { topic: "curtains mouldy", book: "BG", page: "25, 27, 28–30, 105" },
  { topic: "custard tarts", book: "SD", page: "258–60" },
  { topic: "egg-free custard", book: "BG", page: "194–5" },
  { topic: "simple sherry trifle custard", book: "GK", page: "196, 198–9" },
  { topic: "daffodils", book: "GH", page: "92, 167" },
  { topic: "darning", book: "BG", page: "131–4" },
  { topic: "dashboards", book: "CM", page: "175" },
  { topic: "date and orange cake", book: "SD", page: "160-2" },
  { topic: "flexi sticky toffee pudding", book: "GK", page: "151–2" },
  { topic: "de-icer", book: "BG", page: "142–3" },
  { topic: "decanters cleaning", book: "CG", page: "169–70" },
  { topic: "decking", book: "CM", page: "68–70" },
  { topic: "deep cleans", book: "CM", page: "93–122" },
  { topic: "deep cleans", book: "CG", page: "265–6, 268–9" },
  { topic: "deodorant home-made", book: "CM", page: "15, 268–74" },
  { topic: "deodorizing room and fabric spray", book: "CG", page: "182–4" },
  { topic: "descaling irons", book: "CG", page: "42–3" },
  { topic: "descaling kettles", book: "CG", page: "106–7, 272" },
  { topic: "descaling kitchen taps", book: "CG", page: "110, 271" },
  { topic: "detergents Conker", book: "CG", page: "33–4" },
  { topic: "detergents Conker mark II", book: "CM", page: "211–14" },
  { topic: "dishwasher detergent", book: "CG", page: "78–81" },
  { topic: "dishwasher detergent", book: "CM", page: "151–4" },
  { topic: "ivy detergent", book: "CG", page: "31–2" },
  { topic: "ivy detergent", book: "CM", page: "215–17" },
  { topic: "diarrhoea stains", book: "BG", page: "35–7, 56–7" },
  { topic: "diatomaceous earth", book: "CM", page: "198–200, 230" },

  // Page 17
  { topic: "dishcloths", book: "CM", page: "180, 224–5" },
  { topic: "dishwashers cleaning", book: "BG", page: "111–14" },
  { topic: "dishwashers cleaning", book: "CG", page: "82–4, 270" },
  { topic: "dishwashers cleaning", book: "GL", page: "232–3" },
  { topic: "dogs", book: "CM", page: "68, 95, 158, 167, 199, 277–9" },
  { topic: "dogs deterrents", book: "CG", page: "219–20" },
  { topic: "dogs emergency cleans", book: "GL", page: "263–4" },
  { topic: "doughnuts", book: "GK", page: "93–4" },
  { topic: "drains", book: "CM", page: "111, 115" },
  { topic: "drains", book: "CG", page: "272" },
  { topic: "dried fruit", book: "SD", page: "190, 312–14, 94–6, 151–3, 315–18, 160-2, 15, 22, 149–58, 99, 35–6, 225, 90-3, 261–4, 167–8, 150, 156–8, 104, 113–15" },
  { topic: "dried citrus slices", book: "BG", page: "234–5" },
  { topic: "Dry cleaning foam", book: "CM", page: "59–63" },
  { topic: "Dry grease stain remover", book: "CM", page: "56–8, 90" },
  { topic: "Eccles cakes", book: "GK", page: "164, 165–6" },
  { topic: "éclairs", book: "SD", page: "281, 282–5" },
  { topic: "eco-friendly washing-up liquid", book: "CM", page: "7, 56, 183, 205" },
  { topic: "egg shells", book: "CM", page: "200" },
  { topic: "egg-free cakes", book: "SD", page: "213–14" },
  { topic: "egg-free custard", book: "BG", page: "194–5" },

  // Page 18
  { topic: "eggs", book: "GL", page: "37" },
  { topic: "eggs", book: "SD", page: "13–14, 23–4, 119, 125, 232" },
  { topic: "eggs easy trifle sponge", book: "GK", page: "197" },
  { topic: "eggs budget steamed sponge pudding", book: "GK", page: "149" },
  { topic: "eggs fishcakes", book: "GK", page: "19–20" },
  { topic: "eggs kedgeree with oven eggs", book: "GL", page: "63–5" },
  { topic: "eggs minute lemon curd", book: "BG", page: "221–2" },
  { topic: "eggs poached", book: "BG", page: "228–9" },
  { topic: "eggs scrambled", book: "BG", page: "232–3" },
  { topic: "eggs soft- and hard-boiled", book: "BG", page: "230-1" },
  { topic: "elderflower jelly glaze", book: "SD", page: "344–6" },
  { topic: "elderflower and lemon cordial", book: "GK", page: "177" },
  { topic: "elderflower syrup", book: "GH", page: "129–31" },
  { topic: "lemon and elderflower cake", book: "SD", page: "173–5" },
  { topic: "summer lemon and elderflower cheesecake", book: "SD", page: "343–6" },
  { topic: "emulsifiers", book: "CM", page: "14–15, 185, 271, 275" },
  { topic: "enamel cleaning bakeware", book: "CG", page: "128–30" },
  { topic: "energy consumption", book: "BG", page: "7–11, 242" },
  { topic: "Epsom salts", book: "CM", page: "159" },
  { topic: "Epsom salt plant feed", book: "GH", page: "286" },
  { topic: "essential oils", book: "CM", page: "182–3, 232" },

  // Page 19
  { topic: "Easy-Breeze Fabric Spray", book: "CM", page: "235–7" },
  { topic: "eucalyptus essential oil", book: "CM", page: "46, 183, 201–2" },
  { topic: "evaporated milk easy vanilla ice cream", book: "GK", page: "214" },
  { topic: "evaporated milk flexi rice pudding", book: "BG", page: "257–60" },
  { topic: "fabric softener", book: "CM", page: "15, 167–70, 183, 200–3, 209, 217, 218–20, 222, 254" },
  { topic: "fabric conditioner/softener", book: "CG", page: "35–7" },
  { topic: "fake tan stains", book: "GL", page: "261–2" },
  { topic: "fast-fashion", book: "CM", page: "196, 198" },
  { topic: "fats putting down sinks", book: "CM", page: "112–13" },
  { topic: "feeding plants", book: "CG", page: "232–3" },
  { topic: "feeding plants", book: "GH", page: "23–4, 180-3, 285–7" },
  { topic: "fennel crusty dark rye dinner rolls", book: "SD", page: "85–7" },
  { topic: "fennel rye and fennel thins", book: "SD", page: "54–5" },
  { topic: "fire starters, orange peel", book: "CM", page: "85" },
  { topic: "fireplaces cleaning glass door fronts", book: "BG", page: "107–8" },
  { topic: "fireplaces stone and slate hearths", book: "BG", page: "109–10" },
  { topic: "fish fingers", book: "GK", page: "118, 119" },
  { topic: "fishcakes", book: "GK", page: "18, 19–20" },
  { topic: "fish pie luxury", book: "GL", page: "198–200" },
  { topic: "two-salmon plait", book: "GK", page: "158, 159–60" },

  // Page 20
  { topic: "flasks removing odours and stains", book: "BG", page: "91–2" },
  { topic: "floor cleaners", book: "CM", page: "19–21, 23, 45, 47–8, 56" },
  { topic: "floor cleaners", book: "CG", page: "173–5" },
  { topic: "floor cleaners", book: "CM", page: "183" },
  { topic: "flowers dead-heading", book: "GH", page: "100-1" },
  { topic: "flowers drying", book: "GL", page: "111–12, 116–17, 120-2, 215" },
  { topic: "flowers pressed", book: "GL", page: "113–15" },
  { topic: "focaccia", book: "GK", page: "78, 79–80" },
  { topic: "food waste", book: "BG", page: "172" },
  { topic: "food waste", book: "CM", page: "160, 162–3" },
  { topic: "food waste", book: "GH", page: "58, 294–5" },
  { topic: "food waste", book: "GK", page: "7, 13–49" },
  { topic: "food waste", book: "GL", page: "2, 3, 8–11, 13, 33, 42" },
  { topic: "freezing food", book: "BG", page: "8, 151–7" },
  { topic: "freezing bread dough", book: "GK", page: "76–7" },
  { topic: "freezing fresh ginger root", book: "GK", page: "127" },
  { topic: "French beans", book: "GH", page: "97, 115, 151, 153, 299" },
  { topic: "fridges cleaning", book: "CG", page: "117–19, 120-2, 270" },
  { topic: "fridges removing mould and mildew", book: "CG", page: "121–2" },

  // Page 21
  { topic: "fruit drying stone fruit", book: "GH", page: "201–2" },
  { topic: "fruit jam", book: "GK", page: "240, 241–2" },
  { topic: "fruit tree winter wash", book: "GH", page: "247–50" },
  { topic: "fruit juice stains", book: "CG", page: "65" },
  { topic: "fudge slice flexi chocolate", book: "BG", page: "253–6" },
  { topic: "furniture cleaning", book: "BG", page: "78–80" },
  { topic: "furniture cleaning", book: "CG", page: "146–8, 185–6" },
  { topic: "furniture Nancy’s Natural Nurture for leather", book: "CG", page: "150-3" },
  { topic: "furniture polishing wooden", book: "CG", page: "146–8" },
  { topic: "furniture stains", book: "BG", page: "81–2, 118–20" },
  { topic: "furniture stains", book: "CG", page: "154–5" },
  { topic: "ganache chocolate", book: "GK", page: "201–3" },
  { topic: "ganache chocolate", book: "GL", page: "34" },
  { topic: "ganache white chocolate", book: "GK", page: "173" },
  { topic: "garden planning", book: "GH", page: "20-3, 216, 257–60, 291–3" },
  { topic: "garlic", book: "GH", page: "300" },
  { topic: "garlic freezing", book: "BG", page: "152" },
  { topic: "garlic and coriander no-knead bread", book: "SD", page: "107–9" },
  { topic: "garlic harvesting, drying and storing", book: "GH", page: "133–6" },
  { topic: "garlic herb and garlic butter", book: "GH", page: "109–11" },
  { topic: "garlic peeling and prep", book: "BG", page: "156–7" },
  { topic: "garlic planting", book: "GH", page: "114, 118, 119, 220-1, 245" },
  { topic: "gas hobs cleaning", book: "CG", page: "92–4" },

  // Page 22
  { topic: "General polish", book: "CM", page: "15–16, 20, 33, 89, 183" },
  { topic: "gift boxes", book: "GL", page: "94, 207–8" },
  { topic: "ginger freezing", book: "BG", page: "152, 155" },
  { topic: "ginger freezing", book: "SD", page: "161" },
  { topic: "ginger fresh root", book: "GK", page: "127" },
  { topic: "ginger fresh root", book: "SD", page: "161" },
  { topic: "ginger and orange cake", book: "SD", page: "163–4" },
  { topic: "gingerbread houses", book: "GL", page: "151–4" },
  { topic: "Jamaican-style ginger cake", book: "GK", page: "102, 103" },
  { topic: "glass broken", book: "BG", page: "40-1" },
  { topic: "glass cleaning stove doors", book: "BG", page: "107–8" },
  { topic: "glass jars and bottles deep cleaning", book: "GL", page: "97" },
  { topic: "glass jars and bottles recycling", book: "CG", page: "102–3" },
  { topic: "glasses cleaning", book: "CG", page: "256–7" },
  { topic: "glassware cleaning vases and decanters", book: "CG", page: "169–70" },
  { topic: "glassware shining up dull glasses", book: "CG", page: "171–2" },
  { topic: "glue stains", book: "BG", page: "62, 67–8" },
  { topic: "gluten-free recipes", book: "SD", page: "126, 200-1, 207–12, 224–5, 321–2" },
  { topic: "gluten-free bread & butter pudding", book: "GK", page: "35–6" },
  { topic: "gold jewellery cleaning", book: "CG", page: "244–5" },
  { topic: "golden breadcrumbs", book: "GK", page: "14, 15, 74" },
  { topic: "golden syrup cherry and coconut flapjack", book: "BG", page: "199–201" },
  { topic: "Grandma’s beetroot pickle", book: "GH", page: "175–7" },
  { topic: "granola", book: "GH", page: "211–12" },
  { topic: "granola", book: "GK", page: "225" },
  { topic: "granola Sunday sundae", book: "GK", page: "226, 227" },
  { topic: "grass cleaning oven and barbecue racks", book: "CG", page: "87" },

  // Page 23
  { topic: "gravy beef", book: "GK", page: "188, 189–90" },
  { topic: "gravy vegan", book: "GK", page: "210" },
  { topic: "grease stains", book: "CM", page: "20–2, 25, 30, 45, 87, 90, 131, 172–3, 221–2, 249–50" },
  { topic: "green bleach (sodium percarbonate)", book: "CM", page: "7, 18, 23, 30–3, 52, 56, 64, 187" },
  { topic: "green bleach", book: "CG", page: "12, 27" },
  { topic: "green bleach", book: "BG", page: "17–20" },
  { topic: "green bleach", book: "GL", page: "240" },
  { topic: "Green bleach foam", book: "CM", page: "63–7, 146" },
  { topic: "greenfly", book: "GH", page: "112, 113, 114" },
  { topic: "greenhouses", book: "CM", page: "73" },
  { topic: "greenhouses", book: "GH", page: "137, 214–15, 267–72" },
  { topic: "grey water diverters", book: "CM", page: "159–60" },
  { topic: "grout", book: "CM", page: "20-3, 45, 47, 51" },
  { topic: "grout", book: "GL", page: "222" },
  { topic: "hair dye stains", book: "GL", page: "260" },
  { topic: "ham curried ham croquettes", book: "GK", page: "24, 25" },
  { topic: "hand soap Liquid", book: "CM", page: "263–6" },
  { topic: "hands hand cleaner", book: "BG", page: "148" },
  { topic: "hands hand cream", book: "BG", page: "146–8" },
  { topic: "hands hand sanitizer", book: "CG", page: "260-2" },
  { topic: "hands hand warmers", book: "BG", page: "281–3" },
  { topic: "hanging baskets", book: "GH", page: "25, 99–100, 139" },
  { topic: "hanging baskets", book: "GL", page: "80-2" },
  { topic: "hard water descaling irons", book: "CG", page: "42–3" },
  { topic: "hard water descaling kettles", book: "CG", page: "106–7, 272" },
  { topic: "hard water descaling kitchen taps", book: "CG", page: "110, 271" },

  // Page 24
  { topic: "hazelnut praline", book: "SD", page: "356–8" },
  { topic: "herbs drying", book: "GH", page: "76, 133" },
  { topic: "herbs freezing", book: "GH", page: "110, 132–3, 147–8" },
  { topic: "herbs keeping fresh", book: "GL", page: "12" },
  { topic: "herbs keeping fresh", book: "SD", page: "234–5" },
  { topic: "herbs storing", book: "GH", page: "76, 110, 132–3, 146–8, 303" },
  { topic: "herbs storing", book: "GL", page: "12" },
  { topic: "herbs storing", book: "SD", page: "234–5" },
  { topic: "honey fruit loaf", book: "GK", page: "99" },
  { topic: "honey buns", book: "GK", page: "96, 97–8" },
  { topic: "hot cross buns", book: "SD", page: "90-3" },
  { topic: "houseplants", book: "CM", page: "70, 158, 180" },
  { topic: "houseplants", book: "GH", page: "186, 283–7" },
  { topic: "hydrangea heads drying", book: "GL", page: "120-2, 124" },
  { topic: "ice cream easy vanilla", book: "GK", page: "214, 215" },
  { topic: "ice cream no-churn ‘budget’ creamy", book: "BG", page: "226–7" },
  { topic: "ice makers", book: "CM", page: "149–50" },
  { topic: "icing lemon/lime", book: "GK", page: "108, 109" },
  { topic: "induction hobs cleaning", book: "CG", page: "92–4" },
  { topic: "ink stains", book: "CM", page: "20, 35" },
  { topic: "ink stains", book: "BG", page: "63, 67, 71–2" },
  { topic: "insect hotels", book: "GH", page: "223–5, 281–2" },
  { topic: "insect repellents", book: "GH", page: "112, 180-3, 247–50, 297" },
  { topic: "ironing rainwater ironing water", book: "CG", page: "46–7" },
  { topic: "irons care and maintenance", book: "CG", page: "42–7" },
  { topic: "irons cleaning the plate", book: "CG", page: "44–5" },
  { topic: "irons descaling", book: "CG", page: "42–3" },
  { topic: "irons Perfumed distilled ironing water", book: "CM", page: "238–40" },
  { topic: "Italian meringue buttercream", book: "SD", page: "188–90, 208–9" },
  { topic: "ivy Magic suds (ivy detergent)", book: "CG", page: "31–2" },
  { topic: "ivy Magic suds (ivy detergent)", book: "CM", page: "215–17" },

  // Page 25
  { topic: "jacket potatoes universal chilli", book: "GL", page: "58–62" },
  { topic: "jackets re-waxing", book: "BG", page: "124–7" },
  { topic: "jam fruit", book: "GK", page: "240, 241–2" },
  { topic: "jam tarts", book: "BG", page: "187–9" },
  { topic: "jam tarts", book: "GK", page: "243" },
  { topic: "jelly simple sherry trifle", book: "GK", page: "196, 198–9" },
  { topic: "jewellery cleaning gold", book: "CG", page: "244–5" },
  { topic: "jewellery cleaning silver", book: "CG", page: "141–4" },
  { topic: "jewellery pearl necklaces", book: "CG", page: "246–7" },
  { topic: "jewellery tarnished", book: "CM", page: "258–9" },
  { topic: "jumpers shrunken", book: "GL", page: "257–9" },
  { topic: "kale harvesting and storing", book: "GH", page: "241–2, 259, 303" },
  { topic: "kale lemon and pepper kale crisps", book: "GH", page: "253–4" },
  { topic: "kale serve up a savoury souffle", book: "GK", page: "161–2" },
  { topic: "kedgeree with oven eggs", book: "GL", page: "63–5" },
  { topic: "kettles cleaning brass", book: "CG", page: "137–40" },
  { topic: "kettles cleaning copper", book: "CG", page: "123–6" },
  { topic: "kettles descaling", book: "BG", page: "161" },
  { topic: "kettles descaling", book: "CG", page: "106–7, 272" },
  { topic: "kitchens", book: "CM", page: "16–18, 29, 123–54, 162–3" },

  // Page 26
  { topic: "labels removing", book: "CG", page: "104–5" },
  { topic: "lamb universal cottage pie", book: "GK", page: "27–8" },
  { topic: "lambswool fluffies", book: "CM", page: "166–8" },
  { topic: "landfill", book: "CM", page: "129, 164, 206–7, 252" },
  { topic: "lasagne", book: "GK", page: "124, 125" },
  { topic: "lasagne spinach and ricotta", book: "SD", page: "219–21" },
  { topic: "laundry black jeans", book: "GL", page: "252–3" },
  { topic: "laundry cleaning pillows, mattresses, quilts", book: "BG", page: "81–2" },
  { topic: "laundry cold washing", book: "GL", page: "246–54" },
  { topic: "laundry and green bleach", book: "BG", page: "17–20" },
  { topic: "laundry and Pure Magic", book: "BG", page: "12–13" },
  { topic: "laundry reusable make-up pads and flannels", book: "BG", page: "73–4" },
  { topic: "laundry reviving faded cotton", book: "GL", page: "253–4" },
  { topic: "laundry shrunken jumper", book: "GL", page: "257–9" },
  { topic: "laundry stinky second-hand clothes", book: "BG", page: "78–80" },
  { topic: "laundry travel wash", book: "BG", page: "55–7" },
  { topic: "laundry washing machine smells", book: "BG", page: "111–14" },
  { topic: "laundry wedding dresses", book: "BG", page: "75–7" },
  { topic: "laundry detergent Liquid", book: "BG", page: "52–4" },
  { topic: "laundry detergent powder", book: "BG", page: "58–9" },
  { topic: "laundry detergent travel wash", book: "BG", page: "55–7" },
  { topic: "lavender bags", book: "GL", page: "214–16" },
  { topic: "lavender drying", book: "GL", page: "116–17" },
  { topic: "lavender infused oil", book: "CG", page: "176–8" },
  { topic: "Lavender wand", book: "CM", page: "231–4" },
  { topic: "leather cleaning", book: "BG", page: "31–2, 118–20" },
  { topic: "leather cleaning", book: "CG", page: "181" },
  { topic: "leather Nancy’s Natural Nurture for leather", book: "CG", page: "150-3" },
  { topic: "leeks coq au leekie bean stew", book: "GK", page: "138" },

  // Page 27
  { topic: "leek & potato soup", book: "GK", page: "60" },
  { topic: "stir-fried leeks", book: "GH", page: "276–7" },
  { topic: "lemon baked cheesecake", book: "GK", page: "113" },
  { topic: "lemon citrus posset", book: "SD", page: "366–7" },
  { topic: "lemon cleaning chopping boards", book: "BG", page: "222" },
  { topic: "lemon crunchy drizzle muffins", book: "BG", page: "166" },
  { topic: "lemon dried citrus slices", book: "BG", page: "234–5" },
  { topic: "lemon curd", book: "BG", page: "187–9, 221–2" },
  { topic: "lemon curd", book: "GL", page: "133–6" },
  { topic: "lemon curd", book: "SD", page: "193–5, 340-2, 343–6" },
  { topic: "lemon curd tarts", book: "BG", page: "187–9" },
  { topic: "lemon delicious pudding", book: "GK", page: "154, 155" },
  { topic: "lemon drizzle cake", book: "SD", page: "130-1" },
  { topic: "lemon and elderflower cake", book: "SD", page: "173–5" },
  { topic: "lemon and elderflower cordial", book: "GK", page: "177" },
  { topic: "lemon and pepper kale crisps", book: "GH", page: "253–4" },
  { topic: "lemon and raspberry Arctic bundt", book: "SD", page: "375–7" },
  { topic: "lemon sponge pudding", book: "GK", page: "150" },
  { topic: "lemon and yellow courgette cake", book: "GL", page: "143–4" },
  { topic: "lemon yoghurt cake", book: "GL", page: "141–2" },
  { topic: "lemon/lime icing", book: "GK", page: "108, 109" },
  { topic: "meringues with lemon curd", book: "GL", page: "133–6" },
  { topic: "minute lemon curd", book: "BG", page: "221–2" },
  { topic: "summer lemon and elderflower cheesecake", book: "SD", page: "343–6" },
  { topic: "traditional lemon meringue pie", book: "GL", page: "172–5" },
  { topic: "lentils flexi veggie stew", book: "BG", page: "248–52" },
  { topic: "lentils universal cottage pie", book: "GK", page: "27–8" },
  { topic: "lime baked lime, chocolate & coconut cheesecake", book: "GK", page: "110, 111–13" },
  { topic: "lime coconut and lime traybake", book: "SD", page: "137–9" },
  { topic: "lime/lime icing", book: "GK", page: "108, 109" },
  { topic: "lime curd", book: "SD", page: "193–5" },
  { topic: "lime frosting", book: "SD", page: "137–9" },
  { topic: "limescale", book: "BG", page: "50, 112, 161" },
  { topic: "limescale", book: "CM", page: "7–8, 18, 26–7, 29, 34, 51, 83–4, 154, 200-1, 203, 217, 223, 238, 279" },
  { topic: "limescale", book: "GL", page: "226, 228, 230, 232–3, 235, 239, 248–9, 266" },

  // Page 28
  { topic: "limescale spot remover", book: "CG", page: "207–9" },
  { topic: "lining paste", book: "BG", page: "16–17" },
  { topic: "lining paste", book: "GK", page: "152" },
  { topic: "lining paste", book: "GL", page: "131–2" },
  { topic: "lining paste", book: "SD", page: "12" },
  { topic: "lip balm", book: "CG", page: "242–3" },
  { topic: "luffa gourds drying", book: "GH", page: "192–3" },
  { topic: "luffa gourds whitening and sterilising", book: "GH", page: "228–9" },
  { topic: "macarons rose and chocolate", book: "SD", page: "44–8" },
  { topic: "mackerel smoked mackerel canapés", book: "BG", page: "177–8" },
  { topic: "Magic Mixers", book: "CM", page: "14, 15–16, 185–6, 201–2, 213–14, 235–6, 271, 275" },
  { topic: "Magic suds (ivy detergent)", book: "CG", page: "31–2" },
  { topic: "Magic suds (ivy detergent)", book: "CM", page: "215–17" },
  { topic: "make up cleaning brushes and sponges", book: "BG", page: "121–3" },
  { topic: "make up stains", book: "BG", page: "62" },
  { topic: "make up stains", book: "CM", page: "20, 34–5, 47, 245–51" },
  { topic: "make up stains", book: "GL", page: "261–2" },
  { topic: "make up washing reusable make-up pads", book: "BG", page: "73–4" },
  { topic: "malt loaf", book: "SD", page: "205–6" },
  { topic: "marmalade award-winning", book: "BG", page: "271–5" },
  { topic: "marmalade Seville orange", book: "SD", page: "389–91" },
  { topic: "marzipan mini Simnel cakes", book: "GK", page: "168" },
  { topic: "mash oven", book: "GL", page: "195–6" },
  { topic: "mash refresh", book: "GL", page: "197" },
  { topic: "mattresses cleaning", book: "BG", page: "81–2" },
  { topic: "potted meats", book: "GK", page: "16, 17" },

  // Page 29
  { topic: "lemon meringue pie", book: "GL", page: "172–5" },
  { topic: "meringue cake", book: "SD", page: "340-2" },
  { topic: "meringue crown", book: "SD", page: "333–7" },
  { topic: "meringues with lemon curd", book: "GL", page: "133–6" },
  { topic: "meringues half-sugar almond", book: "SD", page: "338–9" },
  { topic: "meringues Italian meringue buttercream", book: "SD", page: "188–90, 208–9" },
  { topic: "metal cleaning", book: "CG", page: "141–5" },
  { topic: "metal cleaning", book: "GL", page: "221–2" },
  { topic: "metal cleaning", book: "GL", page: "275" },
  { topic: "mice deterrents", book: "CG", page: "221–2" },
  { topic: "microplastics", book: "CM", page: "7, 129, 242" },
  { topic: "microwaves cleaning", book: "CG", page: "95–6, 270" },
  { topic: "microwaves food and plate warmers", book: "BG", page: "220" },
  { topic: "microwaves recipes", book: "BG", page: "221–40" },
  { topic: "mildew powdery", book: "CG", page: "228–9" },
  { topic: "mildew powdery", book: "GH", page: "154–5" },
  { topic: "mildew removing from fridge seals", book: "CG", page: "121–2" },
  { topic: "milk-bottle upcycles", book: "GH", page: "272–5" },
  { topic: "mince pies luxury deep-filled", book: "BG", page: "289–94" },
  { topic: "mince pies luxury", book: "SD", page: "261–4" },
  { topic: "mincemeat", book: "SD", page: "261–4, 265–7, 319–20" },
  { topic: "mint creams", book: "BG", page: "286–8" },
  { topic: "mint salad", book: "GK", page: "237" },
  { topic: "mint sauce", book: "GK", page: "20, 237" },
  { topic: "minted pea puree", book: "GK", page: "20" },
  { topic: "mocha log", book: "GK", page: "203" },
  { topic: "mocha macarons", book: "SD", page: "44–8" },
  { topic: "mock Eve’s Pudding", book: "BG", page: "179–81" },
  { topic: "moisture home-made absorber", book: "BG", page: "25–6" },
  { topic: "moisture steamy windows", book: "BG", page: "105–6" },
  { topic: "mould on bags", book: "BG", page: "31–2, 79, 118–20" },
  { topic: "mould bicarbonate of soda cleaner", book: "BG", page: "24–5, 32" },
  { topic: "mould on blinds", book: "BG", page: "25, 27, 28–30, 105" },
  { topic: "mould on bread", book: "BG", page: "128, 173" },
  { topic: "mould on curtains", book: "BG", page: "25, 27, 28–30, 105" },
  { topic: "mould on fabrics", book: "BG", page: "25, 27–30, 105" },
  { topic: "mould on fabrics", book: "GL", page: "237" },
  { topic: "mould in fridges", book: "CG", page: "121–2" },
  { topic: "mould green bleach cleaner", book: "BG", page: "29–31, 33–4" },

  // Page 30
  { topic: "mould on leather bags and shoes", book: "BG", page: "31–2" },
  { topic: "mould Pure Magic cleaner", book: "BG", page: "27–8, 33–4" },
  { topic: "mould in showers", book: "CG", page: "202–4" },
  { topic: "mould and tile grouting", book: "CG", page: "202–4" },
  { topic: "mould on walls, paintwork and wallpaper", book: "BG", page: "24–6" },
  { topic: "mould in washing machines", book: "BG", page: "113" },
  { topic: "mould washing soda cleaner", book: "BG", page: "29–30, 33–4" },
  { topic: "mould on wood", book: "BG", page: "30-1" },
  { topic: "mousse chocolate", book: "BG", page: "248–52" },
  { topic: "mouth guards cleaning", book: "CG", page: "248–9" },
  { topic: "muesli", book: "GK", page: "221" },
  { topic: "muesli", book: "SD", page: "222–3" },
  { topic: "overnight oats", book: "GK", page: "222, 223" },
  { topic: "muffin tins getting pastry into", book: "SD", page: "263" },
  { topic: "muffin tins lining", book: "SD", page: "264" },
  { topic: "muffins chocolate chip", book: "BG", page: "165" },
  { topic: "muffins crunchy lemon drizzle", book: "BG", page: "166" },
  { topic: "muffins quick banana", book: "GK", page: "100, 101" },
  { topic: "muffins raspberry and almond", book: "BG", page: "163–5" },
  { topic: "muffins (English)", book: "GK", page: "88, 89" },
  { topic: "mugs tea stains", book: "CG", page: "75–7" },
  { topic: "chestnut mushroom pasties with gravy", book: "GL", page: "157–61" },
  { topic: "mushroom risotto", book: "BG", page: "243–7" },
  { topic: "mushroom soup", book: "GK", page: "53" },

  // Page 31
  { topic: "mushrooms button", book: "BG", page: "243" },
  { topic: "mushrooms chestnut", book: "BG", page: "243" },
  { topic: "mushrooms cleaning", book: "GK", page: "53" },
  { topic: "mushrooms cup", book: "BG", page: "243" },
  { topic: "mushrooms flat", book: "BG", page: "243" },
  { topic: "mushrooms freezing", book: "GK", page: "53" },
  { topic: "mushrooms oyster", book: "BG", page: "243" },
  { topic: "mushrooms porcini", book: "BG", page: "243" },
  { topic: "mushrooms portobello", book: "BG", page: "243" },
  { topic: "mushrooms shiitake", book: "BG", page: "243" },
  { topic: "mushrooms storing", book: "GK", page: "53" },
  { topic: "mushrooms wild", book: "BG", page: "243" },
  { topic: "mussels cleaning", book: "BG", page: "219" },
  { topic: "mussels steaming", book: "BG", page: "220" },
  { topic: "mustard", book: "GK", page: "187" },
  { topic: "mustard stains", book: "CG", page: "102" },

  // Page 32
  { topic: "nail polish stains on carpet", book: "CG", page: "158" },
  { topic: "nail polish stains on fabric", book: "CG", page: "103" },
  { topic: "nail polish stains on hard surfaces", book: "CG", page: "212" },
  { topic: "napkins folding", book: "GL", page: "284–7" },
  { topic: "napkins starching", book: "GL", page: "283" },
  { topic: "nectarines", book: "GK", page: "135" },
  { topic: "nettle stings", book: "SD", page: "102" },
  { topic: "newspapers recycling", book: "BG", page: "12" },
  { topic: "nightlights", book: "GL", page: "291" },
  { topic: "non-stick pans cleaning", book: "CG", page: "78–9" },
  { topic: "non-stick pans seasoning", book: "GK", page: "24" },
  { topic: "noodles egg", book: "GK", page: "198" },
  { topic: "noodles rice", book: "GK", page: "198" },
  { topic: "noodles soba", book: "GK", page: "198" },
  { topic: "noodles udon", book: "GK", page: "198" },
  { topic: "notebooks", book: "GL", page: "302" },
  { topic: "nougat", book: "BG", page: "253" },
  { topic: "nut allergies", book: "GK", page: "214" },
  { topic: "nut butters", book: "GK", page: "215" },
  { topic: "nut crackers", book: "GK", page: "214" },
  { topic: "nut oils", book: "GK", page: "215" },

  // Page 33
  { topic: "nutmeg", book: "GK", page: "187" },
  { topic: "nuts almonds", book: "GK", page: "214" },
  { topic: "nuts brazil", book: "GK", page: "214" },
  { topic: "nuts cashews", book: "GK", page: "214" },
  { topic: "nuts chestnuts", book: "GK", page: "214" },
  { topic: "nuts hazelnuts", book: "GK", page: "214" },
  { topic: "nuts macadamia", book: "GK", page: "214" },
  { topic: "nuts peanuts", book: "GK", page: "214" },
  { topic: "nuts pecans", book: "GK", page: "214" },
  { topic: "nuts pine", book: "GK", page: "214" },
  { topic: "nuts pistachios", book: "GK", page: "214" },
  { topic: "nuts roasting", book: "GK", page: "215" },
  { topic: "nuts storing", book: "GK", page: "215" },
  { topic: "nuts walnuts", book: "GK", page: "214" },
  { topic: "nylon cleaning", book: "CG", page: "104" },

  // Page 34
  { topic: "oatcakes", book: "GK", page: "223" },
  { topic: "oatmeal", book: "GK", page: "223" },
  { topic: "oats jumbo", book: "GK", page: "223" },
  { topic: "oats porridge", book: "GK", page: "223" },
  { topic: "oats rolled", book: "GK", page: "223" },
  { topic: "objects d'art cleaning", book: "GL", page: "245" },
  { topic: "odours in bins", book: "CG", page: "62" },
  { topic: "odours in carpets", book: "CG", page: "159" },
  { topic: "odours in cars", book: "CG", page: "213" },
  { topic: "odours in fridges", book: "CG", page: "123" },
  { topic: "odours in microwave", book: "CG", page: "128" },
  { topic: "odours on hands", book: "CG", page: "249" },
  { topic: "odours on pets", book: "CG", page: "255" },
  { topic: "odours on shoes", book: "CG", page: "105" },
  { topic: "oil stains on carpet", book: "CG", page: "160" },
  { topic: "oil stains on concrete", book: "CG", page: "214" },
  { topic: "oil stains on fabric", book: "CG", page: "106" },
  { topic: "oil stains on wood", book: "CG", page: "185" },
  { topic: "oil vegetable", book: "GK", page: "188" },
  { topic: "oils essential", book: "GL", page: "292" },
  { topic: "oils finishing", book: "GK", page: "188" },
  { topic: "oils frying", book: "GK", page: "188" },
  { topic: "oils salad", book: "GK", page: "188" },
  { topic: "okra", book: "GK", page: "54" },

  // Page 35
  { topic: "old-fashioned lemonade", book: "BG", page: "254" },
  { topic: "olive oil", book: "GK", page: "189" },
  { topic: "olive oil extra virgin", book: "GK", page: "189" },
  { topic: "olive oil light", book: "GK", page: "189" },
  { topic: "olive oil pomace", book: "GK", page: "189" },
  { topic: "olives black", book: "GK", page: "190" },
  { topic: "olives green", book: "GK", page: "190" },
  { topic: "olives kalamata", book: "GK", page: "190" },
  { topic: "olives stuffed", book: "GK", page: "190" },
  { topic: "omelettes cheese", book: "BG", page: "255" },
  { topic: "omelettes fine herbs", book: "BG", page: "256" },
  { topic: "omelettes plain", book: "BG", page: "255" },
  { topic: "onion soup", book: "GK", page: "55" },
  { topic: "onions brown", book: "GK", page: "54" },
  { topic: "onions caramelising", book: "GK", page: "55" },
  { topic: "onions chopping", book: "GK", page: "55" },
  { topic: "onions pickling", book: "GK", page: "55" },
  { topic: "onions red", book: "GK", page: "54" },
  { topic: "onions roasting", book: "GK", page: "55" },
  { topic: "onions shallots", book: "GK", page: "54" },
  { topic: "onions spring", book: "GK", page: "54" },
  { topic: "onions storing", book: "GK", page: "55" },
  { topic: "onions white", book: "GK", page: "54" },
  { topic: "opal cleaning", book: "GL", page: "246" },
  { topic: "open fires", book: "GL", page: "293" },
  { topic: "oranges blood", book: "GK", page: "136" },
  { topic: "oranges clementines", book: "GK", page: "136" },
  { topic: "oranges mandarins", book: "GK", page: "136" },
  { topic: "oranges navel", book: "GK", page: "136" },
  { topic: "oranges satsumas", book: "GK", page: "136" },
  { topic: "oranges seville", book: "GK", page: "136" },
  { topic: "oranges tangerines", book: "GK", page: "136" },
  { topic: "orchids care", book: "GL", page: "294" },
  { topic: "oregano", book: "GK", page: "191" },
  { topic: "ornaments cleaning", book: "GL", page: "247" },
  { topic: "oven cleaning", book: "CG", page: "124–7" },
  { topic: "oven gloves cleaning", book: "CG", page: "107" },
  { topic: "oxalic acid", book: "BG", page: "35" },
  { topic: "oyster sauce", book: "GK", page: "192" },
  { topic: "oysters opening", book: "BG", page: "221" },
  { topic: "oysters raw", book: "BG", page: "222" },

  // Page 36
  { topic: "paint stains on carpet", book: "CG", page: "161" },
  { topic: "paint stains on fabric", book: "CG", page: "108" },
  { topic: "paint stains on hard surfaces", book: "CG", page: "215" },
  { topic: "paintwork cleaning", book: "CG", page: "186" },
  { topic: "panettone", book: "BG", page: "167" },
  { topic: "pans burnt", book: "CG", page: "79" },
  { topic: "pans cast iron", book: "GK", page: "24" },
  { topic: "pans copper", book: "GK", page: "24" },
  { topic: "pans non-stick", book: "GK", page: "24" },
  { topic: "pans stainless steel", book: "GK", page: "24" },
  { topic: "papaya", book: "GK", page: "137" },
  { topic: "paper recycling", book: "BG", page: "12" },
  { topic: "paprika", book: "GK", page: "187" },
  { topic: "parchment paper", book: "GK", page: "25" },
  { topic: "parmesan cheese", book: "GK", page: "168" },
  { topic: "parsnips", book: "GK", page: "56" },
  { topic: "passion fruit", book: "GK", page: "137" },
  { topic: "pasta dried", book: "GK", page: "198" },
  { topic: "pasta fresh", book: "GK", page: "198" },
  { topic: "pasta shapes", book: "GK", page: "199" },
  { topic: "pasta wholewheat", book: "GK", page: "198" },
  { topic: "pastries chestnut mushroom", book: "GL", page: "157–61" },
  { topic: "pastry choux", book: "BG", page: "168" },
  { topic: "pastry filo", book: "BG", page: "168" },
  { topic: "pastry puff", book: "BG", page: "168" },
  { topic: "pastry shortcrust", book: "BG", page: "168" },
  { topic: "pastry suet", book: "BG", page: "168" },

  // Page 37
  { topic: "pâté chicken liver", book: "BG", page: "257" },
  { topic: "pâté smoked mackerel", book: "BG", page: "258" },
  { topic: "patios cleaning", book: "CG", page: "216" },
  { topic: "pavlova", book: "BG", page: "259" },
  { topic: "peaches", book: "GK", page: "138" },
  { topic: "peanuts", book: "GK", page: "214" },
  { topic: "pears", book: "GK", page: "139" },
  { topic: "peas frozen", book: "GK", page: "57" },
  { topic: "peas garden", book: "GK", page: "57" },
  { topic: "peas mangetout", book: "GK", page: "57" },
  { topic: "peas sugar snap", book: "GK", page: "57" },
  { topic: "pecans", book: "GK", page: "214" },
  { topic: "pectin", book: "BG", page: "260" },
  { topic: "peeling fruit and vegetables", book: "GK", page: "26" },
  { topic: "pencil marks on walls", book: "CG", page: "187" },
  { topic: "peppercorns black", book: "GK", page: "187" },
  { topic: "peppercorns pink", book: "GK", page: "187" },
  { topic: "peppercorns white", book: "GK", page: "187" },
  { topic: "peppers bell", book: "GK", page: "58" },
  { topic: "peppers chilli", book: "GK", page: "58" },
  { topic: "peppers roasting", book: "GK", page: "59" },
  { topic: "perfume stains", book: "CG", page: "109" },
  { topic: "persimmons", book: "GK", page: "140" },
  { topic: "pesto", book: "GK", page: "193" },
  { topic: "pet hair on carpet", book: "CG", page: "162" },
  { topic: "pet hair on fabric", book: "CG", page: "110" },
  { topic: "pet stains on carpet", book: "CG", page: "163" },
  { topic: "pewter cleaning", book: "GL", page: "248" },

  // Page 38
  { topic: "pheasant roasting", book: "BG", page: "223" },
  { topic: "photographs storing", book: "GL", page: "303" },
  { topic: "piano keys cleaning", book: "GL", page: "249" },
  { topic: "pickles", book: "GK", page: "194" },
  { topic: "picnics", book: "GL", page: "304" },
  { topic: "picture frames cleaning", book: "GL", page: "250" },
  { topic: "pies apple", book: "BG", page: "261" },
  { topic: "pies chicken and leek", book: "BG", page: "262" },
  { topic: "pies shepherd's", book: "BG", page: "263" },
  { topic: "pies steak and kidney", book: "BG", page: "264" },
  { topic: "pigeons roasting", book: "BG", page: "224" },
  { topic: "pillows cleaning", book: "CG", page: "111" },
  { topic: "pine nuts", book: "GK", page: "214" },
  { topic: "pineapple", book: "GK", page: "141" },
  { topic: "pistachios", book: "GK", page: "214" },
  { topic: "pitting fruit", book: "GK", page: "27" },
  { topic: "pizza dough", book: "BG", page: "169" },
  { topic: "pizza toppings", book: "BG", page: "170" },
  { topic: "place mats cleaning", book: "CG", page: "80" },
  { topic: "plant pots cleaning", book: "CG", page: "217" },
  { topic: "plants indoor care", book: "GL", page: "295" },
  { topic: "plants outdoor care", book: "SD", page: "103" },
  { topic: "plaster marks on walls", book: "CG", page: "188" },
  { topic: "plastic containers cleaning", book: "CG", page: "81" },
  { topic: "plastic furniture cleaning", book: "CG", page: "218" },

  // Page 39
  { topic: "plate racks cleaning", book: "CG", page: "82" },
  { topic: "plates cleaning", book: "CG", page: "83" },
  { topic: "platinum cleaning", book: "GL", page: "251" },
  { topic: "playing cards cleaning", book: "GL", page: "252" },
  { topic: "plums", book: "GK", page: "142" },
  { topic: "poached eggs", book: "BG", page: "265" },
  { topic: "poaching fruit", book: "GK", page: "28" },
  { topic: "polenta", book: "GK", page: "200" },
  { topic: "polish stains on carpet", book: "CG", page: "164" },
  { topic: "polish stains on fabric", book: "CG", page: "112" },
  { topic: "polishing furniture", book: "CG", page: "189" },
  { topic: "polyester cleaning", book: "CG", page: "113" },
  { topic: "pomegranate", book: "GK", page: "143" },
  { topic: "popcorn", book: "GK", page: "201" },
  { topic: "poppy seeds", book: "GK", page: "216" },
  { topic: "pork belly roasting", book: "BG", page: "225" },
  { topic: "pork chops frying", book: "BG", page: "226" },
  { topic: "pork fillet roasting", book: "BG", page: "227" },
  { topic: "pork joint roasting", book: "BG", page: "228" },
  { topic: "pork sausages frying", book: "BG", page: "229" },
  { topic: "porridge", book: "GK", page: "223" },
  { topic: "port stains", book: "CG", page: "114" },
  { topic: "postcards storing", book: "GL", page: "305" },
  { topic: "potatoes baking", book: "GK", page: "61" },
  { topic: "potatoes boiling", book: "GK", page: "61" },
  { topic: "potatoes chipping", book: "GK", page: "61" },
  { topic: "potatoes mashing", book: "GK", page: "61" },
  { topic: "potatoes roasting", book: "GK", page: "61" },
  { topic: "potatoes salad", book: "GK", page: "61" },
  { topic: "potatoes storing", book: "GK", page: "61" },

  // Page 40
  { topic: "pot-pourri", book: "GL", page: "296" },
  { topic: "pots and pans cleaning", book: "CG", page: "84" },
  { topic: "pottery cleaning", book: "GL", page: "253" },
  { topic: "poultry chicken", book: "BG", page: "230" },
  { topic: "poultry duck", book: "BG", page: "231" },
  { topic: "poultry goose", book: "BG", page: "232" },
  { topic: "poultry turkey", book: "BG", page: "233" },
  { topic: "prawns cleaning", book: "BG", page: "234" },
  { topic: "prawns frying", book: "BG", page: "235" },
  { topic: "prawns raw", book: "BG", page: "236" },
  { topic: "preserving fruit", book: "BG", page: "266" },
  { topic: "pressure cookers", book: "GK", page: "29" },
  { topic: "profiteroles", book: "BG", page: "267" },
  { topic: "prosciutto", book: "GK", page: "175" },
  { topic: "prunes", book: "GK", page: "144" },
  { topic: "puddings bread and butter", book: "BG", page: "268" },
  { topic: "puddings rice", book: "BG", page: "269" },
  { topic: "puddings sticky toffee", book: "BG", page: "270" },
  { topic: "puddings summer", book: "BG", page: "271" },
  { topic: "puddings Yorkshire", book: "BG", page: "272" },
  { topic: "pumpkin", book: "GK", page: "62" },
  { topic: "pumpkin seeds", book: "GK", page: "216" },
  { topic: "Pure Magic cleaner", book: "BG", page: "36" },
  { topic: "purses cleaning", book: "CG", page: "115" },
  { topic: "PVC cleaning", book: "CG", page: "219" },

  // Page 41
  { topic: "quiches cheese and onion", book: "BG", page: "273" },
  { topic: "quiches lorraine", book: "BG", page: "274" },
  { topic: "quiches salmon and broccoli", book: "BG", page: "275" },
  { topic: "quiches spinach and feta", book: "BG", page: "276" },
  { topic: "quince", book: "GK", page: "145" },
  { topic: "quinoa", book: "GK", page: "202" },

  // Page 42
  { topic: "rabbit roasting", book: "BG", page: "237" },
  { topic: "rabbit stew", book: "BG", page: "238" },
  { topic: "radiators cleaning", book: "CG", page: "190" },
  { topic: "radishes", book: "GK", page: "63" },
  { topic: "ragu sauce", book: "BG", page: "277" },
  { topic: "rainwater recycling", book: "BG", page: "13" },
  { topic: "raspberries", book: "GK", page: "146" },
  { topic: "ratatouille", book: "BG", page: "278" },
  { topic: "rattan furniture cleaning", book: "CG", page: "220" },
  { topic: "razor blades cleaning", book: "CG", page: "250" },
  { topic: "recycling glass", book: "BG", page: "11" },
  { topic: "recycling metal", book: "BG", page: "11" },
  { topic: "recycling paper", book: "BG", page: "12" },
  { topic: "recycling plastic", book: "BG", page: "12" },
  { topic: "recycling water", book: "BG", page: "13" },
  { topic: "red wine stains on carpet", book: "CG", page: "165" },
  { topic: "red wine stains on fabric", book: "CG", page: "116" },
  { topic: "redcurrants", book: "GK", page: "147" },
  { topic: "refrigerator cleaning", book: "CG", page: "121–3" },
  { topic: "remote controls cleaning", book: "GL", page: "254" },
  { topic: "rhubarb", book: "GK", page: "148" },
  { topic: "rice basmati", book: "GK", page: "203" },
  { topic: "rice boiling", book: "GK", page: "204" },
  { topic: "rice brown", book: "GK", page: "203" },
  { topic: "rice long grain", book: "GK", page: "203" },
  { topic: "rice pudding", book: "BG", page: "269" },
  { topic: "rice risotto", book: "GK", page: "203" },
  { topic: "rice wild", book: "GK", page: "203" },
  { topic: "risotto mushroom", book: "BG", page: "243–7" },
  { topic: "roasting chicken", book: "BG", page: "230" },
  { topic: "roasting meat", book: "BG", page: "223–33" },
  { topic: "roasting vegetables", book: "GK", page: "30" },

  // Page 43
  { topic: "rolled oats", book: "GK", page: "223" },
  { topic: "rolling pins", book: "GK", page: "31" },
  { topic: "rosemary", book: "GK", page: "191" },
  { topic: "rubber cleaning", book: "CG", page: "221" },
  { topic: "rubbish bins cleaning", book: "CG", page: "62" },
  { topic: "rugs cleaning", book: "CG", page: "166" },
  { topic: "rust stains on carpet", book: "CG", page: "167" },
  { topic: "rust stains on fabric", book: "CG", page: "117" },
  { topic: "rust stains on hard surfaces", book: "CG", page: "222" },

  // Page 44
  { topic: "saffron", book: "GK", page: "187" },
  { topic: "sage", book: "GK", page: "191" },
  { topic: "salad dressings", book: "GK", page: "195" },
  { topic: "salad leaves", book: "GK", page: "64" },
  { topic: "salad spinner", book: "GK", page: "32" },
  { topic: "salmon baking", book: "BG", page: "239" },
  { topic: "salmon frying", book: "BG", page: "240" },
  { topic: "salmon poaching", book: "BG", page: "241" },
  { topic: "salmon smoked", book: "GK", page: "176" },
  { topic: "salt", book: "GK", page: "196" },
  { topic: "sandals cleaning", book: "CG", page: "118" },
  { topic: "sandwiches", book: "GL", page: "306" },
  { topic: "satin cleaning", book: "CG", page: "119" },
  { topic: "saucepan cleaning", book: "CG", page: "84" },
  { topic: "sauces apple", book: "BG", page: "279" },
  { topic: "sauces bechamel", book: "BG", page: "280" },
  { topic: "sauces bread", book: "BG", page: "281" },
  { topic: "sauces cheese", book: "BG", page: "282" },
  { topic: "sauces cranberry", book: "BG", page: "283" },
  { topic: "sauces hollandaise", book: "BG", page: "284" },
  { topic: "sauces mint", book: "BG", page: "285" },
  { topic: "sauces tartare", book: "BG", page: "286" },
  { topic: "sauces tomato", book: "BG", page: "287" },
  { topic: "sausages frying", book: "BG", page: "229" },
  { topic: "sauteing vegetables", book: "GK", page: "33" },
  { topic: "scales kitchen", book: "GK", page: "34" },
  { topic: "scallops cleaning", book: "BG", page: "242" },
  { topic: "scallops frying", book: "BG", page: "243" },
  { topic: "scorched fabric", book: "CG", page: "120" },
  { topic: "scouring pads", book: "CG", page: "85" },

  // Page 45
  { topic: "screens computer cleaning", book: "GL", page: "255" },
  { topic: "screens TV cleaning", book: "GL", page: "256" },
  { topic: "screws and nails storing", book: "GL", page: "307" },
  { topic: "seafood mussels", book: "BG", page: "219" },
  { topic: "seafood oysters", book: "BG", page: "221" },
  { topic: "seafood prawns", book: "BG", page: "234" },
  { topic: "seafood scallops", book: "BG", page: "242" },
  { topic: "seasoning pans", book: "GK", page: "24" },
  { topic: "seaweed", book: "GK", page: "65" },
  { topic: "seeds chia", book: "GK", page: "216" },
  { topic: "seeds flax", book: "GK", page: "216" },
  { topic: "seeds poppy", book: "GK", page: "216" },
  { topic: "seeds pumpkin", book: "GK", page: "216" },
  { topic: "seeds sesame", book: "GK", page: "216" },
  { topic: "seeds sunflower", book: "GK", page: "216" },
  { topic: "self-raising flour", book: "GK", page: "185" },
  { topic: "semolina", book: "GK", page: "205" },
  { topic: "separation of eggs", book: "GK", page: "35" },
  { topic: "serving food", book: "GL", page: "308" },
  { topic: "sesame oil", book: "GK", page: "188" },
  { topic: "sesame seeds", book: "GK", page: "216" },
  { topic: "shallots", book: "GK", page: "54" },
  { topic: "shampooing carpets", book: "CG", page: "168" },
  { topic: "sharpening knives", book: "GK", page: "23" },
  { topic: "shepherd's pie", book: "BG", page: "263" },
  { topic: "shiitake mushrooms", book: "BG", page: "243" },
  { topic: "shoe polish stains", book: "CG", page: "121" },
  { topic: "shoes cleaning", book: "CG", page: "122" },
  { topic: "shortbread", book: "BG", page: "171" },
  { topic: "shortcrust pastry", book: "BG", page: "168" },
  { topic: "shower curtains cleaning", book: "CG", page: "205" },
  { topic: "showers cleaning", book: "CG", page: "202–4" },
  { topic: "shrimps", book: "BG", page: "234" },
  { topic: "silk cleaning", book: "CG", page: "123" },
  { topic: "silver cleaning", book: "GL", page: "257" },
  { topic: "sinks cleaning", book: "CG", page: "86" },
  { topic: "skipping ropes", book: "SD", page: "104" },
  { topic: "slate cleaning", book: "CG", page: "223" },
  { topic: "slow cookers", book: "GK", page: "36" },
  { topic: "smoke stains", book: "CG", page: "191" },
  { topic: "smoked mackerel pâté", book: "BG", page: "258" },
  { topic: "smoked salmon", book: "GK", page: "176" },
  { topic: "smoothies", book: "GK", page: "149" },
  { topic: "snails cleaning", book: "BG", page: "244" },
  { topic: "snails frying", book: "BG", page: "245" },
  { topic: "soap flakes", book: "BG", page: "37" },
  { topic: "soba noodles", book: "GK", page: "198" },
  { topic: "socks cleaning", book: "CG", page: "124" },
  { topic: "soda bicarbonate", book: "BG", page: "24" },
  { topic: "sofa cleaning", book: "CG", page: "192" },
  { topic: "soft fruit", book: "GK", page: "150" },
  { topic: "soft toys cleaning", book: "GL", page: "258" },
  { topic: "soil care", book: "SD", page: "105" },
  { topic: "sole baking", book: "BG", page: "246" },
  { topic: "sole frying", book: "BG", page: "247" },
  { topic: "sorbet", book: "BG", page: "273" },
  { topic: "soufflés cheese", book: "BG", page: "274" },
  { topic: "soufflés chocolate", book: "BG", page: "275" },
  { topic: "soup apple and parsnip", book: "BG", page: "288" },
  { topic: "soup chicken", book: "BG", page: "289" },
  { topic: "soup lentil", book: "BG", page: "290" },
  { topic: "soup mushroom", book: "GK", page: "53" },
  { topic: "soup onion", book: "GK", page: "55" },
  { topic: "soup pea and ham", book: "BG", page: "291" },
  { topic: "soup tomato", book: "BG", page: "292" },
  { topic: "soup vegetable", book: "BG", page: "293" },
  { topic: "sour cream", book: "GK", page: "169" },
  { topic: "soy sauce", book: "GK", page: "197" },
  { topic: "spaghetti", book: "GK", page: "199" },
  { topic: "spatulas", book: "GK", page: "37" },
  { topic: "spices", book: "GK", page: "187" },
  { topic: "spinach", book: "GK", page: "66" },
  { topic: "sponge cakes", book: "BG", page: "172" },
  { topic: "spoons wooden", book: "GK", page: "38" },
  { topic: "spring onions", book: "GK", page: "54" },
  { topic: "squash", book: "GK", page: "67" },
  { topic: "stainless steel cleaning", book: "CG", page: "87" },
  { topic: "stains removal", book: "CG", page: "90–170" },
  { topic: "star anise", book: "GK", page: "187" },
  { topic: "starch", book: "BG", page: "38" },
  { topic: "steak frying", book: "BG", page: "248" },
  { topic: "steak grilling", book: "BG", page: "249" },
  { topic: "steam irons", book: "GL", page: "309" },
  { topic: "steaming food", book: "GK", page: "39" },
  { topic: "stewing food", book: "GK", page: "40" },
  { topic: "sticky toffee pudding", book: "BG", page: "270" },
  { topic: "stir-frying", book: "GK", page: "41" },
  { topic: "stock chicken", book: "BG", page: "294" },
  { topic: "stock vegetable", book: "BG", page: "295" },
  { topic: "stone fruit", book: "GK", page: "151" },
  { topic: "storage solutions", book: "GL", page: "310" },
  { topic: "strawberries", book: "GK", page: "152" },
  { topic: "string", book: "GL", page: "311" },
  { topic: "suede cleaning", book: "CG", page: "125" },
  { topic: "suet pastry", book: "BG", page: "168" },
  { topic: "sugar", book: "GK", page: "198" },
  { topic: "summer pudding", book: "BG", page: "271" },
  { topic: "sunflower oil", book: "GK", page: "188" },
  { topic: "sunflower seeds", book: "GK", page: "216" },
  { topic: "sweeping floors", book: "CG", page: "193" },
  { topic: "sweet potatoes", book: "GK", page: "68" },
  { topic: "sweetcorn", book: "GK", page: "69" },
  { topic: "Swiss roll", book: "BG", page: "173" },
  { topic: "syrup", book: "GK", page: "199" },

  // Page 46
  { topic: "tablecloths cleaning", book: "CG", page: "126" },
  { topic: "tablecloths starching", book: "GL", page: "283" },
  { topic: "tables cleaning", book: "CG", page: "194" },
  { topic: "tahini", book: "GK", page: "216" },
  { topic: "talcum powder stains", book: "CG", page: "127" },
  { topic: "tamarind", book: "GK", page: "187" },
  { topic: "tangerines", book: "GK", page: "136" },
  { topic: "taps cleaning", book: "CG", page: "88" },
  { topic: "taramasalata", book: "GK", page: "177" },
  { topic: "tarragon", book: "GK", page: "191" },
  { topic: "tartare sauce", book: "BG", page: "286" },
  { topic: "tarts apple", book: "BG", page: "261" },
  { topic: "tarts bakewell", book: "BG", page: "296" },
  { topic: "tarts treacle", book: "BG", page: "297" },
  { topic: "tea stains on carpet", book: "CG", page: "169" },
  { topic: "tea stains on fabric", book: "CG", page: "128" },
  { topic: "tea stains on mugs", book: "CG", page: "75–7" },
  { topic: "teapots cleaning", book: "CG", page: "89" },
  { topic: "telephones cleaning", book: "GL", page: "259" },
  { topic: "terracotta cleaning", book: "CG", page: "224" },
  { topic: "thyme", book: "GK", page: "191" },
  { topic: "tiles cleaning", book: "CG", page: "202–4" },
  { topic: "tin foil", book: "GK", page: "25" },
  { topic: "toasting nuts", book: "GK", page: "215" },
  { topic: "toasting seeds", book: "GK", page: "216" },
  { topic: "tofu", book: "GK", page: "206" },
  { topic: "toilet cleaning", book: "CG", page: "206" },
  { topic: "tomato sauce", book: "BG", page: "287" },
  { topic: "tomato soup", book: "BG", page: "292" },
  { topic: "tomatoes cherry", book: "GK", page: "70" },
  { topic: "tomatoes chopped", book: "GK", page: "70" },
  { topic: "tomatoes plum", book: "GK", page: "70" },
  { topic: "tomatoes roasting", book: "GK", page: "71" },
  { topic: "tomatoes storing", book: "GK", page: "71" },
  { topic: "tomatoes sundried", book: "GK", page: "70" },
  { topic: "tongue roasting", book: "BG", page: "250" },
  { topic: "tools cleaning", book: "GL", page: "260" },
  { topic: "tools storing", book: "GL", page: "312" },
  { topic: "toothpaste stains", book: "CG", page: "129" },
  { topic: "toys soft cleaning", book: "GL", page: "258" },
  { topic: "treacle tart", book: "BG", page: "297" },
  { topic: "trout baking", book: "BG", page: "251" },
  { topic: "trout frying", book: "BG", page: "252" },
  { topic: "truffles chocolate", book: "BG", page: "298" },
  { topic: "tuna fresh", book: "GK", page: "178" },
  { topic: "tuna tinned", book: "GK", page: "178" },
  { topic: "turkey roasting", book: "BG", page: "233" },
  { topic: "turmeric", book: "GK", page: "187" },
  { topic: "turnips", book: "GK", page: "72" },
  { topic: "TV screens cleaning", book: "GL", page: "256" },

  // Page 47
  { topic: "udon noodles", book: "GK", page: "198" },
  { topic: "upholstery cleaning", book: "CG", page: "192" },
  { topic: "urine stains on carpet", book: "CG", page: "170" },
  { topic: "urine stains on fabric", book: "CG", page: "130" },

  // Page 48
  { topic: "vacuum cleaners care", book: "GL", page: "313" },
  { topic: "vanilla", book: "GK", page: "187" },
  { topic: "vases cleaning", book: "GL", page: "261" },
  { topic: "veal chops frying", book: "BG", page: "253" },
  { topic: "veal escalopes frying", book: "BG", page: "254" },
  { topic: "veal joint roasting", book: "BG", page: "255" },
  { topic: "vegetable oil", book: "GK", page: "188" },
  { topic: "vegetable soup", book: "BG", page: "293" },
  { topic: "vegetable stock", book: "BG", page: "295" },
  { topic: "vegetables boiling", book: "GK", page: "30" },
  { topic: "vegetables roasting", book: "GK", page: "30" },
  { topic: "vegetables sauteing", book: "GK", page: "33" },
  { topic: "vegetables steaming", book: "GK", page: "39" },
  { topic: "vegetables stewing", book: "GK", page: "40" },
  { topic: "vegetables stir-frying", book: "GK", page: "41" },
  { topic: "velvet cleaning", book: "CG", page: "131" },
  { topic: "venison roasting", book: "BG", page: "256" },
  { topic: "venison steaks frying", book: "BG", page: "257" },
  { topic: "vermouth", book: "GK", page: "207" },
  { topic: "vinegar balsamic", book: "GK", page: "200" },
  { topic: "vinegar cider", book: "GK", page: "200" },
  { topic: "vinegar malt", book: "GK", page: "200" },
  { topic: "vinegar red wine", book: "GK", page: "200" },
  { topic: "vinegar rice", book: "GK", page: "200" },
  { topic: "vinegar white wine", book: "GK", page: "200" },
  { topic: "vinyl floors cleaning", book: "CG", page: "195" },

  // Page 49
  { topic: "waffles", book: "BG", page: "174" },
  { topic: "wallpaper cleaning", book: "CG", page: "196" },
  { topic: "walnuts", book: "GK", page: "214" },
  { topic: "washing machines care", book: "GL", page: "314" },
  { topic: "washing soda", book: "BG", page: "39" },
  { topic: "washing up", book: "CG", page: "50–89" },
  { topic: "water recycling", book: "BG", page: "13" },
  { topic: "watercress", book: "GK", page: "73" },
  { topic: "watermelon", book: "GK", page: "153" },
  { topic: "wax stains on carpet", book: "CG", page: "171" },
  { topic: "wax stains on fabric", book: "CG", page: "132" },
  { topic: "waxing furniture", book: "CG", page: "197" },
  { topic: "whisky stains", book: "CG", page: "133" },
  { topic: "white wine stains on carpet", book: "CG", page: "172" },
  { topic: "white wine stains on fabric", book: "CG", page: "134" },
  { topic: "wholewheat pasta", book: "GK", page: "198" },
  { topic: "wild mushrooms", book: "BG", page: "243" },
  { topic: "wild rice", book: "GK", page: "203" },
  { topic: "windows cleaning", book: "CG", page: "198" },
  { topic: "wine stains", book: "CG", page: "116, 134, 165, 172" },
  { topic: "wood cleaning", book: "CG", page: "180–5" },
  { topic: "wooden spoons", book: "GK", page: "38" },
  { topic: "wool cleaning", book: "CG", page: "135" },
  { topic: "worktops cleaning", book: "CG", page: "199" },
  { topic: "worcestershire sauce", book: "GK", page: "201" },
  { topic: "writing paper", book: "GL", page: "315" },

  { topic: "yeast dried", book: "GK", page: "202" },
  { topic: "yeast fresh", book: "GK", page: "202" },
  { topic: "yoghurt greek", book: "GK", page: "170" },
  { topic: "yoghurt natural", book: "GK", page: "170" },
  { topic: "Yorkshire pudding", book: "BG", page: "272" },

  { topic: "zest of citrus fruit", book: "GK", page: "42" },
  { topic: "zinc cleaning", book: "GL", page: "262" },
  { topic: "zucchini (courgettes)", book: "GK", page: "46" },
];
